# Generated by Django 5.2.8 on 2026-02-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, help_text='خلاصه برای نمایش در لیست')),
                ('content', models.TextField(blank=True, help_text='متن کامل خبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news/videos/')),
                ('link', models.URLField(blank=True, help_text='اگر خبر لینک خارجی دارد', null=True)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory')),
            ],
        ),
    ]
