# Generated by Django 5.2.8 on 2025-12-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='iran_address',
            field=models.TextField(max_length=500, null=True, verbose_name='Iran Address'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='iran_phone',
            field=models.IntegerField(null=True, verbose_name='Iran Phone Number'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mobile_phone',
            field=models.IntegerField(null=True, verbose_name='Mobile Phone Number'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='uae_address',
            field=models.TextField(max_length=500, null=True, verbose_name='UAE Address'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='uae_phone',
            field=models.IntegerField(null=True, verbose_name='UAE Phone Number'),
        ),
    ]
