# Generated by Django 5.2.8 on 2025-11-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات انگلیسی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=200, verbose_name='نام انگلیسی')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_items/', verbose_name='تصویر')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.service', verbose_name='وابسته به خدمت')),
            ],
            options={
                'verbose_name': 'آیتم خدمت',
                'verbose_name_plural': 'آیتم\u200cهای خدمت',
            },
        ),
    ]
