# Generated by Django 5.2.8 on 2025-11-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'Service Item', 'verbose_name_plural': 'Service Items'},
        ),
    ]
