# Generated by Django 5.2.8 on 2026-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_delete_aboutgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='managers/')),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
    ]
